language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Release
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl/

    - os: osx
      sudo: required
      env: 
        - TYPE=Debug
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl/

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
  - python install.py -install -tool -ot

script:
  - cat /proc/cpuinfo || true
  - cmake -DCMAKE_BUILD_TYPE=$TYPE . && make
  - ./run ./bin/triple 12345
  - ./run ./bin/aes 12345
  - ./run ./bin/sha1 12345
  - ./run ./bin/sha256 12345
