apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: marketunits.stable.akridex.com
spec:
  group: stable.akridex.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: marketunits
    singular: marketunit
    kind: MarketUnit
    shortNames:
    - mu
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["cpu","memory","location","secretquantity","secretpricefunc"]
          properties:
            cpu: # 200m
              type: string
              minimum: 1
            memory: # 128Mi
              type: string
              minimum: 1
            secretQuantity:
              type: integer
              minimum: 1
            secretPriceFunc:
              type: string
              minimum: 1
